Update to latest Base-CMS deps
parameter1/industrial-media-websites pull request #129
Opened 2021-05-18 18:17 UTC by B77Mills

- Update vue components to dynamically load
 - Setup GAM, GTM & NativeX to use deferred script loading
 - Upgrade to use 10.24 node version

<img width="1792" alt="Screen Shot 2021-05-18 at 12 56 01 PM" src="https://user-images.githubusercontent.com/3845869/118703121-59f6cf00-b7db-11eb-8c62-ebdc3c17f52f.png">

2021-05-18 21:11 UTC, solocommand approved these changes

2021-05-19 12:33 UTC, zarathustra323 requested changes

2021-05-19 12:33 UTC, zarathustra323 commented on packages/shared/components/document.marko
> +    <!-- <refresh-theme-gam-media-fuse id=site.get("mediaFuse.id") /> -->
I'm assuming the media fuse reference can be removed...

2021-05-19 12:33 UTC, zarathustra323 commented on packages/shared/components/document.marko
> +
This can be done in a different PR, but we should enable P1 events for them as well. Their tenant slug is `indm`

2021-05-19 18:25 UTC, B77Mills commented on packages/shared/components/document.marko
> +
Will Do.

2021-05-21 15:55 UTC, merged