Add oncology & news to navigation & menu
parameter1/industrial-media-websites pull request #271
Opened 2022-10-03 17:29 UTC by jwade1327

<img width="1217" alt="Screen Shot 2022-10-03 at 12 24 03 PM" src="https://user-images.githubusercontent.com/64623209/193640936-5112b778-a22e-43b3-8aa3-f1fa2634b824.png">

2022-10-03 17:29 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [New MDD Topics](https://trello.com/c/Hhz0bmkT/322-new-mdd-topics)

2022-10-04 13:14 UTC, Shinsina requested changes
Oncology would link to this:
![404](https://user-images.githubusercontent.com/46794001/193828379-d5d7844d-a638-4fc5-9707-b6b2f93d93cd.png)

News would link to this:
![Error](https://user-images.githubusercontent.com/46794001/193828380-6373cf0f-3490-4344-a539-4339f5b529b2.png)


Can you confirm that these sections were setup correctly?

2022-10-04 13:33 UTC, jwade1327 commented
@Shinsina I corrected /oncology to /topics/oncology as the alias and the error is because nothing is scheduled to that page. I scheduled a piece of content (see below):
<img width="1792" alt="Screen Shot 2022-10-04 at 8 31 26 AM" src="https://user-images.githubusercontent.com/64623209/193832988-2e051efc-403d-4efc-990e-cd3484dbf000.png">

2022-10-04 13:44 UTC, Shinsina approved these changes

2022-10-04 13:45 UTC, merged