Send `oly_enc_id` as user for BrightCove players
parameter1/industrial-media-websites pull request #316
Opened 2023-05-17 19:12 UTC by Shinsina

![Screenshot from 2023-05-17 13-44-01](https://github.com/parameter1/industrial-media-websites/assets/46794001/e2f6895c-a9ab-4b4a-bd05-f53af85f4cb6)
![Screenshot from 2023-05-17 13-44-43](https://github.com/parameter1/industrial-media-websites/assets/46794001/a419dbde-f0bd-498f-80ca-8acb9993f25d)
![Screenshot from 2023-05-17 14-12-00](https://github.com/parameter1/industrial-media-websites/assets/46794001/20026c4d-afb0-442f-9a0c-a7f62ec60a06)

Reference: https://apis.support.brightcove.com/analytics/dimension-guides/dimension-viewer.html#Send_viewer_id_web_player

2023-05-17 19:12 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Store and retrieve identified user engagement with Brightcove videos](https://trello.com/c/bZWkhm0j/398-store-and-retrieve-identified-user-engagement-with-brightcove-videos)

2023-05-18 11:46 UTC, zarathustra323 requested changes

2023-05-18 11:46 UTC, zarathustra323 commented on packages/global/components/elements/video-player.marko
> +$ const olyEncId = get(req, 'cookies.oly_enc_id');
Whenever the encrypted customer ID is being retrieved it also needs to account for a value present in the request's query string. This should mimic the logic that's done on L99+ of start-server.js found in the global package. Ideally this logic should move to a utility function in the core marko-web-omeda package so it can be re-used anytime the encrypted ID is being accessed.

2023-05-18 21:08 UTC, zarathustra323 approved these changes

2023-05-18 21:09 UTC, merged