Adjust 'Page' content type layout
parameter1/industrial-media-websites pull request #335
Opened 2023-08-03 12:22 UTC by jwade1327

<img width="1321" alt="Screen Shot 2023-08-02 at 3 31 52 PM" src="https://github.com/parameter1/industrial-media-websites/assets/64623209/ca711559-82c1-4144-bab8-5331a86c5363">
<img width="1669" alt="Screen Shot 2023-08-02 at 3 32 10 PM" src="https://github.com/parameter1/industrial-media-websites/assets/64623209/71630132-509d-499f-bd75-5804abe69ac1">
<img width="1678" alt="Screen Shot 2023-08-02 at 3 32 21 PM" src="https://github.com/parameter1/industrial-media-websites/assets/64623209/72724936-4658-4b02-a00e-2cd9f51fd214">

2023-08-03 12:23 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Base editing - bullets not working in Product Video](https://trello.com/c/S5mhpY84/396-base-editing-bullets-not-working-in-product-video)

2023-08-03 12:24 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Indenting in Base for Bullets & Numbers](https://trello.com/c/sZVcY4dt/425-indenting-in-base-for-bullets-numbers)

2023-08-04 12:15 UTC, Shinsina reviewed
@jwade1327 Does this actually solve the problem they're looking to solve? In looking at this it looks like in addition to setting it to be `col-lg-12` when there are no rails, the `max-width` of `content-page-body` should be set to 100% so it fills the space as much as possible like so:
![Screenshot from 2023-08-04 07-12-04](https://github.com/parameter1/industrial-media-websites/assets/46794001/44deb5b2-7f4a-4ea2-8cbb-1d0b8ad395ac)


Possible this has been discussed elsewhere and we're not looking to do this for whatever reason but I think this would address the wrapping concern at least in this instance.

2023-08-04 14:15 UTC, Shinsina requested changes

2023-08-04 15:02 UTC, merged