Setup Section based Native ads (all sites)
parameter1/industrial-media-websites pull request #366
Opened 2024-01-05 20:13 UTC by jwade1327

<img width="1206" alt="Screen Shot 2024-01-05 at 2 11 15 PM" src="https://github.com/parameter1/industrial-media-websites/assets/64623209/658f7b79-b51e-4f60-a2a5-08db262e2940">
<img width="1289" alt="Screen Shot 2024-01-05 at 2 11 08 PM" src="https://github.com/parameter1/industrial-media-websites/assets/64623209/487b3f13-2bbb-4833-ad93-76a8a20a265d">

2024-01-05 20:13 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup Section based NativeX ads](https://trello.com/c/joYyBHuA/471-setup-section-based-nativex-ads)

2024-01-08 14:58 UTC, Shinsina requested changes
See other comment, unsure we subsequently need to add default positions for all those newly added aliases or not.

2024-01-08 14:58 UTC, Shinsina commented on packages/global/components/layouts/content/default.marko
> +            <@native-x indexes=[0] name="related-content" aliases=aliases />
This appears to be in the "Latest In..." block is this intended to use the same Native-X placement as related content?

2024-01-08 15:12 UTC, jwade1327 commented on packages/global/components/layouts/content/default.marko
> +            <@native-x indexes=[0] name="related-content" aliases=aliases />
Yes. It's going to be in the right rail as well as the bottom related block (same as we have for SMG)

2024-01-08 16:01 UTC, Shinsina approved these changes

2024-01-08 16:01 UTC, merged