Update Section based Native ads
parameter1/industrial-media-websites pull request #375
Opened 2024-02-05 17:23 UTC by jwade1327

PROD:
<img width="1184" alt="Screen Shot 2024-02-05 at 11 21 01 AM" src="https://github.com/parameter1/industrial-media-websites/assets/64623209/eb0a282f-55ee-42b8-9033-d159da0c998f">
<img width="1188" alt="Screen Shot 2024-02-05 at 11 21 17 AM" src="https://github.com/parameter1/industrial-media-websites/assets/64623209/b741a023-68e0-4317-a3ca-9d79d3ea56bc">
<img width="1226" alt="Screen Shot 2024-02-05 at 11 21 33 AM" src="https://github.com/parameter1/industrial-media-websites/assets/64623209/2e4e0bc6-f41f-434d-9983-4eb48725ed6c">
DEV:
<img width="1312" alt="Screen Shot 2024-02-05 at 11 21 45 AM" src="https://github.com/parameter1/industrial-media-websites/assets/64623209/c06167d1-f59a-4261-84fe-e4987dd2733c">
<img width="1239" alt="Screen Shot 2024-02-05 at 11 21 51 AM" src="https://github.com/parameter1/industrial-media-websites/assets/64623209/9c226163-1c45-4401-b04d-183be114984c">
<img width="1286" alt="Screen Shot 2024-02-05 at 11 21 59 AM" src="https://github.com/parameter1/industrial-media-websites/assets/64623209/754bb215-110d-467f-a703-7eb5590b3d5a">

2024-02-05 17:26 UTC, Shinsina requested changes

2024-02-05 17:26 UTC, Shinsina commented on packages/global/components/blocks/load-more/content-page.marko
> +$ const nativeXPlacementName = "nativeX.name" || "default";
https://github.com/parameter1/industrial-media-websites/pull/373#discussion_r1476269573

`$ const nativeXPlacementName = nativeX.name || "default";`

2024-02-05 17:32 UTC, jwade1327 commented on packages/global/components/blocks/load-more/content-page.marko
> +$ const nativeXPlacementName = "nativeX.name" || "default";
@Shinsina If I use your above change, the 'related-content' is not respected/picked up, so the ROS ad shows up instead.

2024-02-12 16:47 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup Section based NativeX ads](https://trello.com/c/joYyBHuA/471-setup-section-based-nativex-ads)

2024-02-12 17:38 UTC, jwade1327 commented
@Shinsina Thank you! ⬆️

2024-02-12 17:45 UTC, Shinsina approved these changes

2024-02-12 17:45 UTC, merged